project_id = "nfthqomnugoodruvehko"

[functions.analyze-document]
verify_jwt = true

[functions.analyze-image]
verify_jwt = true

[functions.chat]
verify_jwt = true

[functions.public-api]
verify_jwt = false